name: CDK Deployment
on:
  push:
    tags:
      - v[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          role-session-name: GitHubActions
          aws-region: ap-northeast-1
      - name: CDK Deploy
        run: |
          docker pull ghcr.io/yoshitaka-motomura/php:8.2.17
          npx cdk deploy --require-approval never
        env:
          AWS_REGION: ap-northeast-1
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          IMAGE_TAG: ${{ github.ref_name }}
